Модель исключений [[РНР]] напоминает модель исключений других языков программирования. PHP умеет выбрасывать — [`throw`](https://www.php.net/manual/ru/language.exceptions.php) — и ловить — [`catch`](https://www.php.net/manual/ru/language.exceptions.php#language.exceptions.catch) — исключения. Код заключают в блок [`try`](https://www.php.net/manual/ru/language.exceptions.php), чтобы упростить обработку вероятных исключений. Каждому блоку [`try`](https://www.php.net/manual/ru/language.exceptions.php) указывают как минимум один блок [`catch`](https://www.php.net/manual/ru/language.exceptions.php#language.exceptions.catch) или [`finally`](https://www.php.net/manual/ru/language.exceptions.php#language.exceptions.finally).
[set_exception_handler()](https://www.php.net/manual/ru/function.set-exception-handler.php) устанавливает функцию, которую PHP вызовет вместо блока 
## Пример выброса исключения

```php
<?php  
  
function inverse($x) {  
if (!$x) {  
throw new Exception('Деление на ноль.');  
}  
return 1 / $x;  
}  
  
try {  
echo inverse(5) . "\n";  
echo inverse(0) . "\n";  
} catch (Exception $e) {  
echo 'PHP перехватил исключение: ', $e->getMessage(), "\n";  
}  
  
// Продолжить выполнение  
echo "Привет, мир\n";  
  
?>
```

Ответ от Блок tey catch всегда будет отталкиваться от блока "finally" в конструкцию try и catch
#### В блоке catch можно обрабатывать несколько типов исключений
```php
try {  
throw new MyException();  
} catch (MyException | MyOtherException $e) {  
var_dump(get_class($e));  
}
```
![[Pasted image 20240415182929.png]]